version: "3.8"

services:
  agent:
    image: portainer/agent:latest
    environment:
      - AGENT_CLUSTER_ADDR=tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - ${SWARM_NETWORK}
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - ${SWARM_NETWORK}

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:9000/api/status >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

      resources:
        reservations:
          cpus: "0.10"
          memory: 128M
        limits:
          cpus: "0.50"
          memory: 512M

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
      rollback_config:
        order: stop-first
      labels:
        - "traefik.enable=true"

        - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_URL}`)"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"

        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        - "traefik.http.routers.portainer.service=portainer"

        - "traefik.http.services.portainer.loadbalancer.sticky.cookie=true"
        - "traefik.http.services.portainer.loadbalancer.sticky.cookie.name=PORTAINER_STICKY"

        - "traefik.http.middlewares.portainer-secure-headers.headers.stsSeconds=31536000"
        - "traefik.http.middlewares.portainer-secure-headers.headers.stsIncludeSubdomains=true"
        - "traefik.http.middlewares.portainer-secure-headers.headers.stsPreload=true"
        - "traefik.http.middlewares.portainer-secure-headers.headers.browserXssFilter=true"
        - "traefik.http.middlewares.portainer-secure-headers.headers.contentTypeNosniff=true"
        - "traefik.http.routers.portainer.middlewares=portainer-secure-headers@docker"

volumes:
  portainer_data:
    driver: local

networks:
  ${SWARM_NETWORK}:
    external: true
